from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

mainMenuIS = InlineKeyboardMarkup(row_width=4)
btn_is_11 = InlineKeyboardButton(text='ИС-11', callback_data='btn_is_11')
btn_is_12 = InlineKeyboardButton(text='ИС-12', callback_data='btn_is_12')
btn_is_13 = InlineKeyboardButton(text='ИС-13', callback_data='btn_is_13')
btn_is_14 = InlineKeyboardButton(text='ИС-14', callback_data='btn_is_14')
btn_is_15 = InlineKeyboardButton(text='ИС-15', callback_data='btn_is_15')
btn_is_16 = InlineKeyboardButton(text='ИС-16', callback_data='btn_is_16')
btn_is_17 = InlineKeyboardButton(text='ИС-17', callback_data='btn_is_17')
btn_is_18 = InlineKeyboardButton(text='ИС-18', callback_data='btn_is_18')

mainMenuIS.insert(btn_is_11)
mainMenuIS.insert(btn_is_12)
mainMenuIS.insert(btn_is_13)
mainMenuIS.insert(btn_is_14)
mainMenuIS.insert(btn_is_15)
mainMenuIS.insert(btn_is_16)
mainMenuIS.insert(btn_is_17)
mainMenuIS.insert(btn_is_18)

mainMenuSA = InlineKeyboardMarkup(row_width=4)
btn_sa_11 = InlineKeyboardButton(text='СА-11', callback_data='btn_sa_11')
btn_sa_12 = InlineKeyboardButton(text='СА-12', callback_data='btn_sa_12')
btn_sa_13 = InlineKeyboardButton(text='СА-13', callback_data='btn_sa_13')
btn_sa_14 = InlineKeyboardButton(text='СА-14', callback_data='btn_sa_14')
btn_sa_15 = InlineKeyboardButton(text='СА-15', callback_data='btn_sa_15')
btn_sa_16 = InlineKeyboardButton(text='СА-16', callback_data='btn_sa_16')
btn_sa_17 = InlineKeyboardButton(text='СА-17', callback_data='btn_sa_17')

mainMenuSA.insert(btn_sa_11)
mainMenuSA.insert(btn_sa_12)
mainMenuSA.insert(btn_sa_13)
mainMenuSA.insert(btn_sa_14)
mainMenuSA.insert(btn_sa_15)
mainMenuSA.insert(btn_sa_16)
mainMenuSA.insert(btn_sa_17)

mainMenuIBT = InlineKeyboardMarkup(row_width=4)
btn_ibt_11 = InlineKeyboardButton(text='ИБТ-11', callback_data='btn_ibt_11')
btn_ibt_12 = InlineKeyboardButton(text='ИБТ-12', callback_data='btn_ibt_12')
btn_ibt_13 = InlineKeyboardButton(text='ИБТ-13', callback_data='btn_ibt_13')
btn_ibt_14 = InlineKeyboardButton(text='ИБТ-14', callback_data='btn_ibt_14')

mainMenuIBT.insert(btn_ibt_11)
mainMenuIBT.insert(btn_ibt_12)
mainMenuIBT.insert(btn_ibt_13)
mainMenuIBT.insert(btn_ibt_14)

mainMenuIBA = InlineKeyboardMarkup(row_width=4)
btn_iba_11 = InlineKeyboardButton(text='ИБA-11', callback_data='btn_iba_11')
btn_iba_12 = InlineKeyboardButton(text='ИБA-12', callback_data='btn_iba_12')
btn_iba_13 = InlineKeyboardButton(text='ИБA-13', callback_data='btn_iba_13')
btn_iba_14 = InlineKeyboardButton(text='ИБA-14', callback_data='btn_iba_14')

mainMenuIBA.insert(btn_iba_11)
mainMenuIBA.insert(btn_iba_12)
mainMenuIBA.insert(btn_iba_13)
mainMenuIBA.insert(btn_iba_14)
